/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.time.LocalDateTime;

/**
 *
 * @author Aldriv
 */
public class Calc extends javax.swing.JFrame {
    public float n1;
    public float n2;
    public String operador;
    
private void guardarEnHistorial(String operacion, float resultado) {
    try (FileWriter fw = new FileWriter("bitacoraCalculadora.txt", true);
         BufferedWriter bw = new BufferedWriter(fw);
         PrintWriter out = new PrintWriter(bw)) {

        String linea = java.time.LocalDateTime.now() + " - " + operacion + " = " + resultado;
        out.println(linea);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el historial.");
    }
}

private void mostrarHistorial() {
    StringBuilder contenido = new StringBuilder();
    try (java.util.Scanner scanner = new java.util.Scanner(new java.io.File("bitacoraCalculadora.txt"))) {
        while (scanner.hasNextLine()) {
            contenido.append(scanner.nextLine()).append("\n");
        }
    } catch (java.io.FileNotFoundException e) {
        JOptionPane.showMessageDialog(this, "No se encontró el archivo de historial.");
        return;
    }

    JOptionPane.showMessageDialog(this, contenido.toString(), "Historial de Cálculos", JOptionPane.INFORMATION_MESSAGE);
}
private void reiniciarCalculadora() {
    this.n1 = 0;
    this.n2 = 0;
    this.operador = "";
    this.pantalla.setText(""); // Limpia el campo de texto de la pantalla
}


    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calc.class.getName());

    /**
     * Creates new form Calc
     */
    public Calc() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pantalla = new javax.swing.JLabel();
        jb_c = new javax.swing.JButton();
        jb_7 = new javax.swing.JButton();
        jb_division = new javax.swing.JButton();
        jb_8 = new javax.swing.JButton();
        jb_9 = new javax.swing.JButton();
        jb_1 = new javax.swing.JButton();
        jb_4 = new javax.swing.JButton();
        jb_multiplicacion = new javax.swing.JButton();
        jb_5 = new javax.swing.JButton();
        jb_2 = new javax.swing.JButton();
        jb_6 = new javax.swing.JButton();
        jb_3 = new javax.swing.JButton();
        jb_punto = new javax.swing.JButton();
        jb_resta = new javax.swing.JButton();
        jb_0 = new javax.swing.JButton();
        jb_igual = new javax.swing.JButton();
        jb_suma = new javax.swing.JButton();
        menu_op = new javax.swing.JMenuBar();
        opciones = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        historial = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        man_usu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pantalla.setBackground(new java.awt.Color(255, 255, 255));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        pantalla.setOpaque(true);
        pantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pantallaKeyTyped(evt);
            }
        });

        jb_c.setText("C");
        jb_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cActionPerformed(evt);
            }
        });

        jb_7.setText("7");
        jb_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_7ActionPerformed(evt);
            }
        });

        jb_division.setText("/");
        jb_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_divisionActionPerformed(evt);
            }
        });

        jb_8.setText("8");
        jb_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_8ActionPerformed(evt);
            }
        });

        jb_9.setText("9");
        jb_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_9ActionPerformed(evt);
            }
        });

        jb_1.setText("1");
        jb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_1ActionPerformed(evt);
            }
        });
        jb_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_1KeyPressed(evt);
            }
        });

        jb_4.setText("4");
        jb_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_4ActionPerformed(evt);
            }
        });

        jb_multiplicacion.setText("*");
        jb_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_multiplicacionActionPerformed(evt);
            }
        });

        jb_5.setText("5");
        jb_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_5ActionPerformed(evt);
            }
        });

        jb_2.setText("2");
        jb_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_2ActionPerformed(evt);
            }
        });

        jb_6.setText("6");
        jb_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_6ActionPerformed(evt);
            }
        });

        jb_3.setText("3");
        jb_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_3ActionPerformed(evt);
            }
        });

        jb_punto.setText(".");
        jb_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_puntoActionPerformed(evt);
            }
        });

        jb_resta.setText("-");
        jb_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_restaActionPerformed(evt);
            }
        });

        jb_0.setText("0");
        jb_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_0ActionPerformed(evt);
            }
        });

        jb_igual.setText("=");
        jb_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_igualActionPerformed(evt);
            }
        });

        jb_suma.setText("+");
        jb_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jb_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jb_suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_punto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jb_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jb_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        opciones.setText("Opciones");

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        opciones.add(nuevo);

        historial.setText("Historial");
        historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialActionPerformed(evt);
            }
        });
        opciones.add(historial);

        menu_op.add(opciones);

        ayuda.setText("Ayuda");

        man_usu.setText("Manual de Usuario");
        man_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_usuActionPerformed(evt);
            }
        });
        ayuda.add(man_usu);

        menu_op.add(ayuda);

        setJMenuBar(menu_op);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_4ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"4");
    }//GEN-LAST:event_jb_4ActionPerformed

    private void jb_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_6ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"6");
    }//GEN-LAST:event_jb_6ActionPerformed

    private void jb_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sumaActionPerformed
        // TODO add your handling code here:
        this.n1=Float.parseFloat(this.pantalla.getText());
        this.operador="+";
        this.pantalla.setText("");
    }//GEN-LAST:event_jb_sumaActionPerformed

    private void jb_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_0ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"0");
    }//GEN-LAST:event_jb_0ActionPerformed

    private void jb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_1ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"1");
    }//GEN-LAST:event_jb_1ActionPerformed

    private void jb_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_2ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"2");
    }//GEN-LAST:event_jb_2ActionPerformed

    private void jb_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_3ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"3");
    }//GEN-LAST:event_jb_3ActionPerformed

    private void jb_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_5ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"5");
    }//GEN-LAST:event_jb_5ActionPerformed

    private void jb_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_7ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"7");
    }//GEN-LAST:event_jb_7ActionPerformed

    private void jb_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_8ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"8");
    }//GEN-LAST:event_jb_8ActionPerformed

    private void jb_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_9ActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText(this.pantalla.getText()+"9");
    }//GEN-LAST:event_jb_9ActionPerformed

    private void jb_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cActionPerformed
        // TODO add your handling code here:
        this.pantalla.setText("");
    }//GEN-LAST:event_jb_cActionPerformed

    private void jb_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_igualActionPerformed
        // TODO add your handling code here:
        this.n2=Float.parseFloat(this.pantalla.getText());
        float resultado = 0;
        
          switch (this.operador) {
        case "+":
            resultado = this.n1 + this.n2;
            break;
        case "-":
            resultado = this.n1 - this.n2;
            break;
        case "*":
            resultado = this.n1 * this.n2;
            break;
        case "/":
            if (this.n2 == 0) {
                this.pantalla.setText("Error");
                return;
            } else {
                resultado = this.n1 / this.n2;
            }
            break;
    }
          this.pantalla.setText(sincero(resultado));
          
          guardarEnHistorial(this.n1 + " " + this.operador + " " + this.n2, resultado);
    }//GEN-LAST:event_jb_igualActionPerformed

    private void jb_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_restaActionPerformed
        // TODO add your handling code here:
        this.n1=Float.parseFloat(this.pantalla.getText());
        this.operador="-";
        this.pantalla.setText("");
    }//GEN-LAST:event_jb_restaActionPerformed

    private void jb_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_multiplicacionActionPerformed
        // TODO add your handling code here:
        this.n1=Float.parseFloat(this.pantalla.getText());
        this.operador="*";
        this.pantalla.setText("");
    }//GEN-LAST:event_jb_multiplicacionActionPerformed

    private void jb_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_divisionActionPerformed
        // TODO add your handling code here:
        this.n1=Float.parseFloat(this.pantalla.getText());
        this.operador="/";
        this.pantalla.setText("");
    }//GEN-LAST:event_jb_divisionActionPerformed

    private void jb_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_puntoActionPerformed
        // TODO add your handling code here:
        if(!(this.pantalla.getText().contains("."))){
        this.pantalla.setText(this.pantalla.getText()+".");
        }
    }//GEN-LAST:event_jb_puntoActionPerformed

    private void jb_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_1KeyPressed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
         reiniciarCalculadora();
    }//GEN-LAST:event_nuevoActionPerformed

    private void historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialActionPerformed
        // TODO add your handling code here:
        mostrarHistorial();
    }//GEN-LAST:event_historialActionPerformed

    private void pantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pantallaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

    if (Character.isDigit(c) || c == '.' || c == '+' || c == '-' || c == '*' || c == '/' || c == '\b') {
        java.awt.Toolkit.getDefaultToolkit().beep(); // Suena beep si es válido
    } else {
        evt.consume(); // Bloquea teclas no válidas
    }
    }//GEN-LAST:event_pantallaKeyTyped

    private void man_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_usuActionPerformed
        // TODO add your handling code here:
        String mensaje = """
        Manual del Usuario - Calculadora
        
        1. Ingresa los números utilizando el teclado o los botones.
        2. Usa los botones de operaciones: +, -, *, /
        3. Presiona "=" para obtener el resultado.
        4. Menú Opciones > Historial guarda tus operaciones en un archivo.
        5. Menú Opciones > Nuevo limpia la pantalla.
        6. Cada tecla válida emite un beep.
        """;
    JOptionPane.showMessageDialog(this, mensaje, "Manual del Usuario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_man_usuActionPerformed
    
    public String sincero(float result){
        String retorno="";        
        retorno=Float.toString(result);
        
        if(result%1==0){
            retorno=retorno.substring(0,retorno.length()-2);
        }
        
        return retorno;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem historial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_0;
    private javax.swing.JButton jb_1;
    private javax.swing.JButton jb_2;
    private javax.swing.JButton jb_3;
    private javax.swing.JButton jb_4;
    private javax.swing.JButton jb_5;
    private javax.swing.JButton jb_6;
    private javax.swing.JButton jb_7;
    private javax.swing.JButton jb_8;
    private javax.swing.JButton jb_9;
    private javax.swing.JButton jb_c;
    private javax.swing.JButton jb_division;
    private javax.swing.JButton jb_igual;
    private javax.swing.JButton jb_multiplicacion;
    private javax.swing.JButton jb_punto;
    private javax.swing.JButton jb_resta;
    private javax.swing.JButton jb_suma;
    private javax.swing.JMenuItem man_usu;
    private javax.swing.JMenuBar menu_op;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JMenu opciones;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
